# Generated by Django 5.0.4 on 2024-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('customer', 'Customer'), ('admin', 'Admin')], max_length=10),
        ),
    ]