# Generated by Django 5.0.6 on 2024-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='Artist_id',
            field=models.CharField(default=123456789, max_length=50),
            preserve_default=False,
        ),
    ]
