# Generated by Django 5.0.6 on 2024-05-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_type', models.CharField(max_length=50)),
                ('stroke_style', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('color_temparature', models.CharField(max_length=50)),
                ('depth', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=50)),
                ('complexity', models.CharField(max_length=50)),
            ],
        ),
    ]
