# Generated by Django 5.0.6 on 2024-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='styles',
            old_name='color_temparature',
            new_name='key_characteristics',
        ),
        migrations.RenameField(
            model_name='styles',
            old_name='stroke_style',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='styles',
            name='period',
            field=models.PositiveIntegerField(default=123456789),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='styles',
            name='theme',
            field=models.CharField(default=123456789, max_length=50),
            preserve_default=False,
        ),
    ]
