# Generated by Django 5.0.6 on 2024-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('artist_id', models.PositiveIntegerField()),
                ('artist_name', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('supplier_id', models.PositiveIntegerField()),
                ('supplier_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
