# Generated by Django 5.0.6 on 2024-06-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsupplies', '0002_remove_artsupplies_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artsupplies',
            name='image_url',
        ),
        migrations.AddField(
            model_name='artsupplies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
